title: Olivia Chang
description: Developer, designer, student, and major nerd.
baseurl: ""
url: ""
email: "hello@oliviachang.me"
# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
collections:
  projects:
    title: Project
    output: true
    permalink: "/:title"
    layout: project
  client_work:
    title: Client Work
    output: true
    permalink: "/:title"
    layout: project
sass:
  style: compressed