title: Olivia Chang
description: Developer, designer, student, and major nerd.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
email: "hello@oliviachang.me"
# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
collections:
  projects:
    title: Project
    output: true
    permalink: "/:title"
    layout: project